### ISSUE TITLE
Sysmon: Performance considerations

### ISSUE THREAD

**Issue by mschilt** [MicrosoftDocs/sysinternals#114]
Q1: Does Sysmon evaluate rules in a sequential way? 
If yes. Would it make sense to re-order the policy and move the most frequently used rules to the top so we get a hit as fast as possible?

Q2: Image Condition
Someone mentioned in the sysinternals (now technet) forums that the performance hit is reduced when the filter "image" ist used instead of "is".  Could you please clarify whether you expect a noticable difference.
<Image condition="Is">calc.exe</Image>..  vs. <Image condition="image">calc.exe</image>

**Comment by analyze-v** [comment]
Sorry for the delay in responding. We typically track this type of query through the sysinternals forums and are just now clearing the github backlog. 

It really depends on how the rules are written. Rules for the same field are always combined using OR so if we have an onmatch="include" ruleset for example we will work through the rules in order until we find a match then stop the search.
When this question was posted the same also applied to rules for different fields on the same event which (contrary to the documentation) were also combined using OR. Note though that rules for each field are checked in the order that they are specified in the manifest rather than necessarily in the order they are given in the config file.   

Now that we have rule groups this changes because if rules are AND'd together we need to check all rules (or at least until a non-match is found).  Hopefully this makes sense?

And contrary to speculation I'm not aware of any significant overhead difference for is vs image.

MarkC (MSFT)
