### ISSUE TITLE
Sysmon parsing issue when empty field in forwardedevents

### ISSUE THREAD

**Issue by sisecbe** [MicrosoftDocs/sysinternals#126]
Using Sysmon in conjunction with Windows event forwarding, when a field is empty in a Sysmon log (for example SourcePortName in EventID 3) the windows event viewer can't parse the event correctly. For the local sysmon logs everything is ok, but in the forwarded events on the WEC all fields are shifted.
example:

SourcePortName: false
DestinationIsIpv6: 40.113.200.201
DestinationIp: microsoft.com
DestinationHostname: 443
DestinationPort: %16
DestinationPortName: %17

**Comment by jokezone** [comment]
Are you confirming this using the raw event XML on the WEC server or the event forwarded to your SIEM? If the WEC Sysmon event is not identical to the WEC client Sysmon event, then this is a problem with Windows Event Forwarding. I have personally experienced this behavior on the SIEM side, and that was caused by a bug in the SIEM.

**Comment by sisecbe** [comment]
Hi, I confirm it is on the WEC server itself (in the forwarded events logs) only when using the 'binary' format on the clients (/cf:Events). When using XML format it is working fine.

**Comment by lukekim** [comment]
Thanks for reporting this, we are investigating.

**Comment by analyze-v** [comment]
Thank you for reporting this. I have added it to the Sysmon backlog
