### ISSUE TITLE
The index.md page is outdated

### ISSUE THREAD

**Issue by epikgit** [MicrosoftDocs/sysinternals#139]
The page downloads/index.md is outdated. 

For example Autoruns has been released in December 11th according to https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns (version 13,93) while the global download page https://docs.microsoft.com/en-us/sysinternals/downloads/ asserts it has been released on July the 5th and the version is 13,90.

**Comment by analyze-v** [comment]
Thanks for reporting and apologies for the delay in responding.
This has since been superseded. However it does highlight what is a manual step in our publishing process. Thus while there is no longer anything to fix I have added an item to out tooling backlog to look at how we might automate this process
