### ISSUE TITLE
More mistakes in sysinternals/sysinternals/downloads/sysmon.md

### ISSUE THREAD

**Issue by qux-bbb** [MicrosoftDocs/sysinternals#164]
**First problem**  
In the picture:  
![image](https://user-images.githubusercontent.com/18598419/55221956-a9699200-5245-11e9-9faa-b018598c0ed1.png)  
It says, "Do not log process termination", but the value of "onmatch" is "include". It should be "exclude".  

**Second problem**  
The example of "RuleGroup" can not work.   
When I write them to a file "example.xml" as follows:  
```xml
<Sysmon schemaversion="4.20">
    <!-- Capture all hashes -->
    <HashAlgorithms>*</HashAlgorithms>
    <EventFiltering>
        <Group name="group 1" groupRelation="and">
            <ProcessCreate onmatch="include">
                <Image condition="contains">timeout.exe</Image>
                <CommandLine condition="contains">100</CommandLine>
            </ProcessCreate>
        </Group>
        <Group groupRelation="or">
            <ProcessTerminate onmatch="include"/>
            <Image condition="contains">timeout.exe</Image>
            <Image condition="contains">ping.exe</Image>
        </Group>
        <ImageLoad onmatch="include"/>
    </EventFiltering>
</Sysmon>
```
And I use a command like this:  
`sysmon -c example.xml`  
Then the output is:  
```
Error: Incorrect XML configuration: example.xml
Reason: ????? 'EventFiltering' ???????? 'Group' ??????
??: RuleGroup, ProcessCreate, FileCreateTime, NetworkConnect, ProcessTerminate, DriverLoad, ImageLoad, CreateRemoteThread, RawAccessRead, ProcessAccess, FileCreate, RegistryEvent, FileCreateStreamHash, PipeEvent, WmiEvent?
```

 Who can help me?

**Comment by analyze-v** [comment]
Hello
many thanks for reporting these. The ProcessTerminate logic is actually correct: It states that we should only include anything that matches the filter but then doesn't specify any filter items so there is nothing to match. Hopefully that makes sense

You were correct with the second problem though. This was a syntax error because the ProcessTerminate tag was prematurely closed. I have resolved this in both the documentation on the website and in the tool itself (when you run sysmon -help config). The latter will be available in the next published release.

Regards

Mark Cook (MSFT)

**Comment by qux-bbb** [comment]
Yeah，Get it.  
Thanks.
