### ISSUE TITLE
Sdelete may allocate file in wrong place when cleaning system drive

### ISSUE THREAD

**Issue by Gallium70** [MicrosoftDocs/sysinternals#214]
Sdelete may allocate file in wrong place when cleaning system drive
在清理系统分区的时候，Sdelete可能会把临时文件创建到错误的位置

When calling 'sdelete -c C:\' (where C:\ is the system drive), SDelete would allocate the zero file in the %TEMP% directory, instead of the root dir when it is performed on other drives. However, there is a possibility that this file would not be allocated in (as in my case, precisely speaking, it is my User dir being moved to another drive, and I created a symbolic link in its original place), so I'm not sure whether SDelete cleaned free space in the system drive as expected.
在使用SDelete清理系统分区的时候，SDelete会将文件创建到TEMP文件夹内，而清理其他分区时会直接创建在根目录下。如果TEMP文件夹并不在系统分区内（我把用户文件夹移到了另一个分区，在原来的位置上创建了一个符号链接），那么就无法确定SDelete有没有正确清理系统分区的空闲空间。

My folder structure looks like this:

 - C:\
   + User (folder)
       - [Username] (a symbolic link)

- D:\\
  + User (folder)
      - Username (folder)
         + Appdata (folder)
             - Local (folder)
                + Temp (folder, where %TEMP% actually is)

![20190628175543](https://user-images.githubusercontent.com/52118815/60338939-dc085f80-99d9-11e9-9423-15367d7c676a.png)

**Comment by foxmsft** [comment]
I ran Windows with the user profile directory on a different drive for many years. I did this on Windows 7, 8 and on 10, with the method described on [SevenForums](https://www.sevenforums.com/tutorials/87555-user-profile-change-default-location.html) - editing the registry and making the correct entry from `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList` point to the new profile on the new drive.

Moving the user profile directory with such a method is just a hack, and it just accidentally works in this case, so users are pretty much on their own should they run into any problems.

While updating Windows 8 (also to 8.1) the updater would often fail with my administrator account on drive D instead of C. As a temporary solution I created a local administrator account with the user profile directory in the normal place (under `C:\Users`) and ran the updates while logged in with that account. I think that this workaround should be fine for your specific `sdelete` scenario too, as the tool is not designed to follow shortcuts.

I think that this PR can be closed as it's not related to the Sysinternals documentation, but to the tools themselves. The [Sysinternals region of the TechNet forums](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals) is the official place to get proper tool help from users knowledgeable with the tools and from the developers themselves, so please create a new thread there if you're still facing problems.

**Comment by brendanhoar** [comment]
The following in a cmd window seems to workaround the issue of the wrong drive having zeros written:
```
mkdir C:\temp
set TEMP=C:\temp
sdelete -z C:\
```

In my case, C:\Users is a link to E:\Users (where my profiles are stored).
