### ISSUE TITLE
Sysmon not installing from under %systemroot%

### ISSUE THREAD

**Issue by theaquamarine** [MicrosoftDocs/sysinternals#227]
Hi, hope this is the right place for bug reports!

I'm encountering an issue when `sysmon -i` is run from a path under `%systemroot%`, sysmon isn't installing correctly:
- sysmon.exe isn't copied to `%systemroot%`
- sysmondrv.sys doesn't appear to be created anywhere
- The sysmon service lists the original file path as its path.

![sysmon](https://user-images.githubusercontent.com/111144/61168955-f439bc00-a54d-11e9-9525-5a6da575d885.png)

Thanks!

**Comment by analyze-v** [comment]
Hello
this has been a known issue for some time. However I am pleased to say that this has now been resolved and the fix will be available shortly in Sysmon 10.3 and later.

Thanks for reporting. If you have any other issues the best place to report them is either via the Sysinternals forums (https://forum.sysinternals.com) or via email to syssite@microsoft.com. We do monitor this site too but not as actively since this is mainly for documentation on the site itself.

MarkC (MSFT)
