### ISSUE TITLE
RAMMAP：Add up all memory usage in Processes/File Summary tab not match Use Counts

### ISSUE THREAD

**Issue by aobuke** [MicrosoftDocs/sysinternals#284]
For example, sum up all Total/Active memory numbers in Processes/File Summray to a value but it doesn't match the value in Use Counts. However, the values in Use Counts are OK. I want to reduce my overall memory usage from removing both processes counts and specific processes that uses lots of memory.

**Comment by foxmsft** [comment]
@aobuke I've taken the liberty of creating a post on the [TechNet forums](https://social.technet.microsoft.com/Forums/en-US/3f3a7540-262f-4348-abc1-771c7da5a1b2/add-up-all-memory-usage-in-processesfile-summary-tab-not-match-use-counts?forum=miscutils), which is the recommended way for reporting bugs or sending help queries to other Sysinternals users or devs. 

This issue here should be closed, but please, post a reply under that TechNet forum topic I created, so you receive notifications upon further activity on the topic.
