### ISSUE TITLE
RegJump: Please support a specific scheme

### ISSUE THREAD

**Issue by LEORChn** [MicrosoftDocs/sysinternals#290]
Please support a specific scheme.
Example:

regedit:hkcu\Control Panel\Desktop\WindowArrangementActive

So I can guide user change their registry easier on webpage.

**Comment by foxmsft** [comment]
This issue can be closed as it's not directly related to documentation.

I created a feature suggestion [on the TechNet support forum](https://social.technet.microsoft.com/Forums/en-US/6a977cb4-d042-43bd-88c6-717cce1b0648/regjump-please-support-a-custom-uri-scheme?forum=utilsuggestions), which is the recommended source for such inquiries. @LEORChn just post an answer in the thread there so that you receive notifications for new activity.
