### ISSUE TITLE
psexec64 on Win10 and remote client WS2012R2

### ISSUE THREAD

**Issue by xeriax** [MicrosoftDocs/sysinternals#327]
I have a problem with psexec64 on a Win10 machine and remote client is WS2012R2.
psexec64 is v2.2

when I turn off the firewall on the remote client then psexec64 works perfectly on Win10, once I turn on the firewall on remote client the error message appears "Network path not found"!

At this moment,
I run the same psexec64 and same command on a Win7 machine,then it works properly.

I also try the same tool and command on a WS2012R2 machine, and everything is fine.

So, I am suspecting this is a setting issue on Win10 or something wrong on the psexec64.

I try to disable all firewall on Win10 but it doesn't work.

Any idea?

**Comment by foxmsft** [comment]
Hey, you might have better success directing your query to [the Sysinternals Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-sysinternals-pstools.html) site. It's mostly empty now since the forums just transitioned to the new website, but there are quite a few users around who can share their experience with the tools. Closing this issue here.
