### ISSUE TITLE
Findlinks v1.1 Not working on Windows 10

### ISSUE THREAD

**Issue by google-mirror** [MicrosoftDocs/sysinternals#428]
Findlinks v1.1 - Locate file hard links
Copyright (C) 2011-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

Index:  0x000280EE
Links:  0

**Comment by glenn-slayden** [comment]
I thought so too, but while writing up a more detailed, corroborating report here in this comment, I just realized what's wrong:

> ***findlinks.exe does not include the filename that you provide as one of the links***.

In other words, the filename that you enter on the command line is excluded from the hard links that are reported. You can see this from the following:

<pre><b>findlinks -nobanner C:\windows\system32\notepad.exe</b>
C:\windows\system32\notepad.exe
        Index:  0x000CF5CE
        Links:  2

Linking files:
C:\Windows\notepad.exe
C:\Windows\WinSxS\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe</pre>

<pre><b>findlinks -nobanner C:\windows\notepad.exe</b>
C:\windows\notepad.exe
        Index:  0x000CF5CE
        Links:  2

Linking files:
C:\Windows\WinSxS\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe
C:\Windows\System32\notepad.exe</pre>

<pre><b>findlinks -nobanner C:\Windows\WinSxS\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe</b>
C:\windows\winsxs\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe
        Index:  0x000CF5CE
        Links:  2

Linking files:
C:\Windows\notepad.exe
C:\Windows\System32\notepad.exe</pre>

As you can see, depending on which link you specify, only the other two out of the three are reported ***and counted***. It doesn't seem very intuitive to me, especially because most NTFS documentation states that "once there are zero links, the actual `$DATA` content of the file is deleted," I guess the rationale is that you must "obviously" already know the name in the full path you've given.

The `fsutil` output seems more logical:

<pre><b>fsutil hardlink list C:\Windows\notepad.exe</b>
\Windows\notepad.exe
\Windows\WinSxS\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe
\Windows\System32\notepad.exe</pre>

This `fsutil` syntax allows you to get the *total* number of links like so:

<pre><b>fsutil hardlink list C:\Windows\notepad.exe | wc -l</b>
      3</pre>

This number equals the number of links reported by `findlinks.exe` ***plus one***, and thus will always be greater than zero, as commonly expected. For completeness, note that the hard links info for a file can also be obtained like this:

<pre><b>fsutil file layout C:\Windows\notepad.exe</b>

********* File 0x00020000000cf5ce *********
File reference number   : 0x00020000000cf5ce
File attributes         : 0x00000620: Archive | Sparse | Reparse point
File entry flags        : 0x00000000
Link (ParentID: Name)   : 0x0002000000076671: HLINK Name   : \Windows\notepad.exe
Link (ParentID: Name)   : 0x00090000000abbb9: NTFS+DOS Name: \Windows\WinSxS\amd64_microsoft-windows-notepad_31bf3856ad364e35_10.0.19041.1320_none_e3d2189d253c2e6b\notepad.exe
Link (ParentID: Name)   : 0x0002000000076d33: HLINK Name   : \Windows\System32\notepad.exe
Creation Time           : 11/10/2021 1:15:01
    ...etc...
Stream                  : 0x030  ::$FILE_NAME
    Attributes          : 0x00000000: *NONE*
    Flags               : 0x0000000c: Resident | No clusters allocated
    Size                : 88
    Allocated Size      : 88
Stream                  : 0x030  ::$FILE_NAME
    Attributes          : 0x00000000: *NONE*
    Flags               : 0x0000000c: Resident | No clusters allocated
    Size                : 88
    Allocated Size      : 88
Stream                  : 0x030  ::$FILE_NAME
    Attributes          : 0x00000000: *NONE*
    Flags               : 0x0000000c: Resident | No clusters allocated
    Size                : 88
    Allocated Size      : 88
Stream                  : 0x080  ::$DATA
    ...etc...</pre>

**Comment by glenn-slayden** [comment]
Therefore, I recommend closing this issue as **not-a-bug**.

**Comment by foxmsft** [comment]
Thanks for the explanation!
