### ISSUE TITLE
Symbol download failed when use process monitor

### ISSUE THREAD

**Issue by qiannjust** [MicrosoftDocs/sysinternals#67]
Hi,

We only push pdb file in my company's symbol server.
i find the process monitor can't show the function in UI.  I checked the dbghelp log, i find the tool first download the excute file from symbol server, when it fail, it search in the local, and it success. it start find the pdb file, but it don't search from symbol server, it only find the local, so it failed.

May this tool support search the pdb file from symbol server when search the execute file from symbol server failed?
Thank you.

**Comment by lukekim** [comment]
Thanks for reporting this, we will investigate.

**Comment by analyze-v** [comment]
Hello
Thanks for reporting this and apologies for the delay in responding. Github is really for documentation issues and bugs are generally reported via the sysinternals form at forum.sysinternals.com.

Am I correct in understanding that the problem is process monitor is failing to find your symbols in your private symbol server so you are having to copy them locally >

**Comment by analyze-v** [comment]
Had no response to this so closing. Please get back to us via the sysinternals forum or by email at syssite@microsoft.com if you experience any further difficulties.
